version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      PGSQL_USERNAME: postgres
      PGSQL_PASSWORD: postgres
      PGSQL_DATABASE: postgres

  postgres:
    image: postgres:14
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  db-init:
    image: postgres:14
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'postgres'\" | grep -q 1 || psql -U postgres -c \"CREATE DATABASE postgres WITH OWNER = postgres ENCODING = 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TABLESPACE=pg_default CONNECTION LIMIT=-1\""
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
